---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: tag
  image: rancher/dapper:v0.4.2
  commands:
    - echo "${DRONE_TAG}-amd64" | sed -e 's/+/-/g' >.tags
  volumes:
    - name: docker
      path: /var/run/docker.sock
- name: fossa
  image: registry.suse.com/suse/sle15:15.3
  failure: ignore
  environment:
    FOSSA_API_KEY:
      from_secret: FOSSA_API_KEY
  commands:
    - zypper -n install curl unzip
    - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/spectrometer/master/install.sh | sh"
    - fossa analyze
    - fossa test
  when:
    instance:
      - drone-publish.k3s.io
    ref:
      include:
        - "refs/heads/master"
    event:
      - push
      - tag
- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    build_args:
      - ARCH=amd64
      - TAG=${DRONE_TAG}
    password:
      from_secret: docker_password
    repo: "rancher/k3s-upgrade"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: tag
  image: rancher/dapper:v0.4.2
  commands:
    - echo "${DRONE_TAG}-arm64" | sed -e 's/+/-/g' >.tags
  volumes:
    - name: docker
      path: /var/run/docker.sock
- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    build_args:
      - ARCH=arm64
      - TAG=${DRONE_TAG}
    password:
      from_secret: docker_password
    repo: "rancher/k3s-upgrade"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: tag
  image: rancher/dapper:v0.4.2
  commands:
    - echo "${DRONE_TAG}-arm" | sed -e 's/+/-/g' >.tags
  volumes:
    - name: docker
      path: /var/run/docker.sock
- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    build_args:
      - ARCH=arm
      - TAG=${DRONE_TAG}
    password:
      from_secret: docker_password
    repo: "rancher/k3s-upgrade"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: s390x

platform:
  os: linux
  arch: amd64

node:
  arch: s390x

steps:
- name: tag
  image: rancher/dapper:v0.5.8
  commands:
    - echo "${DRONE_TAG}-s390x" | sed -e 's/+/-/g' >.tags
  volumes:
    - name: docker
      path: /var/run/docker.sock
- name: docker-publish
  image: rancher/drone-images:docker-s390x
  settings:
    dockerfile: Dockerfile
    build_args:
      - ARCH=s390x
      - TAG=${DRONE_TAG}
    password:
      from_secret: docker_password
    repo: "rancher/k3s-upgrade"
    username:
      from_secret: docker_username
  volumes:
    - name: socket
      path: /var/run/docker.sock
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
  - name: manifest
    image: plugins/docker
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    settings:
      dry_run: true
      dockerfile: Dockerfile.manifest
      repo: "rancher/k3s-upgrade-manifest"
      build_args_from_env:
        - DOCKER_USERNAME
        - DOCKER_PASSWORD
        - DRONE_TAG
    when:
      instance:
        - drone-publish.k3s.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

depends_on:
  - amd64
  - arm64
  - arm
