FROM alpine:3.22

COPY --from=plugins/manifest:1.2.3 /bin/* /bin/

ARG DOCKER_USERNAME
ENV DOCKER_USERNAME $DOCKER_USERNAME

ARG DOCKER_PASSWORD
ENV DOCKER_PASSWORD $DOCKER_PASSWORD

ARG DRONE_TAG
ENV DRONE_TAG $DRONE_TAG

RUN apk upgrade -U \
 && apk cache clean \
 && rm -rf /var/cache/apk/*

COPY ./scripts/manifest /bin/

RUN manifest
